### ISSUE TITLE
Static web stack files missing?

### ISSUE THREAD

**Issue by Unintendedz** [aws-samples/subtitle-generator-cdk-app#2]
Hi, Thanks for this awesome sample; I learned much from it.
But after the `cdk deploy --all,` I opened the URL in the `StaticWebStack.StaticWebDistributionUrl` output, and it seems some js files are missing.
![image](https://user-images.githubusercontent.com/64687143/188637313-4ee3b157-1d70-4000-988e-a00c14536ca9.png)

Or I'm doing something wrong?

@masangbeom

**Comment by masangbeom** [comment]
I'm so sorry. I saw the issue too late.
Static web application files were missing by `.gitignore`.
Now, It's fixed :)
